<a href="https://colab.research.google.com/github/ompatel420/ML-Practicals/blob/main/ML_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
dataset1 =pd.read_csv('/content/drive/MyDrive/ML/Dataset/dataset1.csv')
dataset1

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset1.shape

(10, 4)

In [ ]:
dataset1.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:
dataset1.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
dataset1.head()
dataset1.info()
dataset1.describe()
dataset1.isnull().sum()
dataset1.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

(10, 4)

In [ ]:
X = dataset1.iloc[:, :-1].values
y = dataset1.iloc[:, -1].values

In [ ]:
imputer_mean = SimpleImputer(strategy='mean')
X_imputed = imputer_mean.fit_transform(X[:, 1:3])  # Apply to Age and Salary
print(X_imputed)

[[4.40000000e+01 7.20000000e+04]
 [2.70000000e+01 4.80000000e+04]
 [3.00000000e+01 5.40000000e+04]
 [3.80000000e+01 6.10000000e+04]
 [4.00000000e+01 6.37777778e+04]
 [3.50000000e+01 5.80000000e+04]
 [3.87777778e+01 5.20000000e+04]
 [4.80000000e+01 7.90000000e+04]
 [5.00000000e+01 8.30000000e+04]
 [3.70000000e+01 6.70000000e+04]]